### ISSUE TITLE
Help Using Region Mask w. xarray and geopandas

### ISSUE THREAD

**Issue by lwasser** [mathause/regionmask#188]
Hi there,
I wondered if you could provide some guidance on using regionmask. i've gone through the docs and the blog post on making masks but i'm getting a bit stuck implementing this package into my lessons (i'm teaching netcdf to my students).
I want to be able to spatially subset the data by a polygon shape (for instance summary of changes in temp by state). I'm looking at this tool and salem right now and am trying to understand the differences and really trying to get the mask to work. 

Can you look at my code below and guide me through what i'm doing wrong? I know there is a difference between  CRS 4326 and these netcdf files that are in lat/lon wgs84 but global coordinates (no negatives). Am i doing something wrong in creating the mask or applying it or both? Thank you for your time!! 

```
import os

import numpy as np
import pandas as pd
import xarray as xr
import geopandas as gpd
import earthpy as et

# Get netcdf file
data_path_monthly = 'http://thredds.northwestknowledge.net:8080/thredds/dodsC/agg_macav2metdata_tasmax_BNU-ESM_r1i1p1_rcp45_2006_2099_CONUS_monthly.nc'

# Open up the data
with xr.open_dataset(data_path_monthly) as file_nc:
    monthly_forecast_temp_xr = file_nc

# xarray object
monthly_forecast_temp_xr


# Download natural earth data to generate AOI
et.data.get_data(url="https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_1_states_provinces_lakes.zip")

# However you want to create this path to get the data! 
states_path = "earthpy-downloads/ne_50m_admin_1_states_provinces_lakes"
states_path = os.path.join(states_path, "ne_50m_admin_1_states_provinces_lakes.shp")

states_gdf = gpd.read_file(states_path)

cali_region = states_gdf.name == "California"
# What is this doing vs the mask creation below?
cali_bound = regionmask.from_geopandas(cali_bound, 
                                          names="name", 
                                          name="state", 
                                          abbrevs="name_alt")

# Create data array for mask - i'm confused by this step vs the boundary step above
lon = np.arange(235, 292)
lat = np.arange(25, 49)
# Create a 3d mask 
mask = regionmask.mask_3D_geopandas(cali_bound, lon, lat)
# Just to make processing better slice out a few months
time_slice = monthly_forecast_temp_xr.sel(time=slice('2099-10-25', '2099-12-15'))

# This throws - ValueError: Cannot apply_along_axis when any iteration dimensions are 0
masked_temp = time_slice.where(mask)

# I know you can also do something like this below but i'm not sure how that works either
regionmask.mask.mask_3D(airtemps)
```

**Comment by mathause** [comment]
Thanks for your interest in regionmask.

I do not use salem myself. As I understand the difference is that salem can handle coordinate transformations while regionmask currently assumes all data is in WSG84. With salem you can only handle one region/ polygon at a time while regionmask can handle several regions at once. I think salem was rather designed for regional climate models (like WRF) in mind while regionmask was designed for global models.

I am no expert in coordinate systems but I think  EPSG:4326 _is_ WGS 84.

```python
# What is this doing vs the mask creation below?
cali_bound = regionmask.from_geopandas(cali_bound, ...)
```
regionmask has it's own data container (called `Regions`). Here you are transforming a `geopandas.GeoDataFrame` to a `Regions` object, which you could then use to create a mask. So `regionmask.mask_3D_geopandas` does not create a mask, yet.

You can also directly create a mask from a `GeoDataFrame` like you do here:
```python
mask = regionmask.mask_3D_geopandas(cali_bound, lon, lat)
```
However, you need to pass the `lat` and `lon` of the object you want to mask! So here `monthly_forecast_temp_xr.lon` and `monthly_forecast_temp_xr.lat`. So the get the `ValueError` because the lat/ lon of the mask and the DataSet are not the same.

I created a minimal example, masking out California:

```python
import matplotlib.pyplot as plt
import regionmask
import xarray as xr

# Get netcdf file
data_path_monthly = 'http://thredds.northwestknowledge.net:8080/thredds/dodsC/agg_macav2metdata_tasmax_BNU-ESM_r1i1p1_rcp45_2006_2099_CONUS_monthly.nc'

# Open up the data
ds = xr.open_dataset(data_path_monthly)

# slice out a few months
ds_slice = ds.sel(time=slice('2099-10-25', '2099-12-15'))

# the US states are available here:
us_states_50 = regionmask.defined_regions.natural_earth.us_states_50
print(us_states_50)

# you can select california like so
california = us_states_50[["CA"]]
print(california)

# create a mask
mask_ca = california.mask(ds)

mask_ca.plot()

ds_slice.where(mask_ca)

# set everything outside of california to NaN
# California has the number 4
ds_slice_ca = ds_slice.where(mask_ca == 4)

# plot the first timestep
plt.figure()
ds_slice_ca.air_temperature.isel(time=0).plot()
```

**Comment by lwasser** [comment]
@mathause thank you so much for your time in responding here. the example above worked well for me and now i think i better understand how `regionmask` works! I am going to include this in some of our online lessons on earthdatascience.org as well! i'll close this for the time being.
